when:
  - event: push
    branch: main

# .woodpecker.yaml

steps:
  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: hariharan1520/ubbuntu
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
